version: '3'
services:
  
  api:
    #container_name: nodejs-api
    build: .

    scale: 2
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 3000:3000
